id: P000157
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །བྱང་ཆུབ་ཀྱི་སྤྱོད་པ་ལ་འཇུག་པའི་རྣམ་པར་བཤད་པ་དགོངས་པ་ངེས་པར་གསལ་བ་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། བླ་མ་དམ་པ་བསོོད་ནམས་རྒྱལ་མཚན།
  layers:
  - book_title
  - author
  - quotation
  - sabche
  - yigchung
  id: IBA-SG-02-1
web_metadata:
  title:
    en: Brilliant Intention:An Explanation of the Bodhicharyavatara
    bo: བྱང་ཆུབ་ཀྱི་སྤྱོད་པ་ལ་འཇུག་པའི་རྣམ་བཤད་དགོངས་པ་ངེས་གསལ།
  collection:
    en: IBA Sonam Gyaltsen Series–  Book 2
    bo: བསོོད་ནམས་རྒྱལ་མཚན་རྩོམ་བྲིས།–  དེབ། ༢
  author:
    en: Lama Dampa Sonam Gyaltsen
    bo: བླ་མ་དམ་པ་བསོོད་ནམས་རྒྱལ་མཚན།
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-SG-02-1
  category:
    en: Bodhicharyavatara
    bo: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-SG-02-1.epub
  description:
    en: This commentary sheds light to the ultimate aspiration of the Great Indian
      Pandit Shantideva’s text.
    bo: ཐེག་པ་ཆེན་པོ་ལམ་ཚང་ལ་མ་ནོར་བར་བསྟན་པའི་གཞུང་གི་འགྲེལ་པ།
